name: CI/CD Pipeline


on:
  push:
    branches:
      - main
#on:
#  release:
#    types: published

#env:
  #IMAGE_TAG: ${{ github.sha }}
  #IMAGE_TAG: ${{ github.event.release.tag_name }}
env:
   CR_REGISTRY: crpqj6bs28mvdpattggi
   CR_REPOSITORY: teman4ik

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v2

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
        
  #     - name: Login to Yandex Cloud Container Registry
  #       id: login-cr
  #       uses: yc-actions/yc-cr-login@v2
  #       with:
  #        yc-sa-json-credentials: "${{ secrets.YC_SA_JSON_CREDENTIALS }}"

  #     - name: Build, tag, and push image to Yandex Cloud Container Registry
  #       env:
  #         CR_REGISTRY: crpqj6bs28mvdpattggi
  #         CR_REPOSITORY: teman4ik
  #       run: |
  #         docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:1 .
  #         docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:1


  deploy:
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v2
        with:
         yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
        
      - name: Pull docker image
        run: |
          docker pull cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:1

      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v4.0.0
        with:
         method: kubeconfig
         kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
         context: yc-tema-cluster

      - name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v5
        with:
         namespace: 'default'
         manifests: |
            service.yaml
            deployment.yaml
         images: 'cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:1'
         

